In [1]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("race_results_cleaned.csv")
df.head()

,platz,stn,name,verein,birthyear,ak-pl.,mw-pl.,zeit,last_name,first_name,gender,is_male,age,age_group,zeit_min,pace,speed,percentile
0,1,6459,STÜTZEL Simon,LG Region Karlsruhe,1986.0,1. M,1. M,27:35,STÜTZEL,Simon,M,1,40.0,40-49,27.58,3.10,19.337687,0.0174
1,2,2,STÖCKL Christian,Feuerwehr Liedolsheim,1988.0,2. M,2. M,28:56,STÖCKL,Christian,M,1,38.0,30-39,28.93,3.25,18.435306,0.0349
2,3,119,MÖHLER Samuel,Regierungspräsidium Karlsruhe,1996.0,3. M,3. M,29:00,MÖHLER,Samuel,M,1,30.0,30-39,29.00,3.26,18.390807,0.0523
3,4,13,WILKENS Hannes,LG Region Karlsruhe,2002.0,4. M,4. M,29:22,WILKENS,Hannes,M,1,24.0,19-24,29.37,3.30,18.159122,0.0698
4,5,12,WEBER Yannik,LG Region Karlsruhe,1992.0,5. M,5. M,29:27,WEBER,Yannik,M,1,34.0,30-39,29.45,3.31,18.109793,0.0872

In [9]:
# df[df['first_name'] == 'Marcel']
df[df['age'] < 15].head(20)

,platz,stn,name,verein,birthyear,ak-pl.,mw-pl.,zeit,last_name,first_name,gender,is_male,age,age_group,zeit_min,pace,speed,percentile
69,70,474,SCHORB Julian,LG Region Karlsruhe,2012.0,4. M U19,64. M,33:51,SCHORB,Julian,M,1,14.0,<18,33.85,3.81,15.755787,1.2208
108,109,412,MATZERATH Ole,LG Region Karlsruhe,2014.0,6. M U19,103. M,34:40,MATZERATH,Ole,M,1,12.0,<18,34.67,3.90,15.383138,1.9009
349,350,3138,ROSENGARDT Kilian,Gymnasium Neureut,2012.0,21. M U19,324. M,38:17,ROSENGARDT,Kilian,M,1,14.0,<18,38.28,4.31,13.932429,6.1039
381,382,3249,MAURER Jonathan,Humboldt-Gymnasium Karlsruhe,2013.0,26. M U19,353. M,38:34,MAURER,Jonathan,M,1,13.0,<18,38.57,4.34,13.827674,6.6620
417,418,4616,SCHLEIPEN Ben,LG Region Karlsruhe,2013.0,28. M U19,384. M,38:52,SCHLEIPEN,Ben,M,1,13.0,<18,38.87,4.37,13.720952,7.2899
448,449,3091,GERBER Philipp,Gymnasium Neureut,2012.0,30. M U19,411. M,39:03,GERBER,Philipp,M,1,14.0,<18,39.05,4.39,13.657706,7.8305
653,654,933,HEWEL Niclas,NaN,2012.0,44. M U19,595. M,40:42,HEWEL,Niclas,M,1,14.0,<18,40.70,4.58,13.104015,11.4057
697,698,3391,KNAM Noah,Karlsruhe,2015.0,45. M U19,634. M,40:58,KNAM,Noah,M,1,11.0,<18,40.97,4.61,13.017657,12.1730
779,780,1440,RAHMEL Otto,NaN,2015.0,51. M U19,706. M,41:26,RAHMEL,Otto,M,1,11.0,<18,41.43,4.66,12.873121,13.6031
786,787,4424,CHRIST Jonas,Krokodile Karlsruhe,2014.0,53. M U19,712. M,41:30,CHRIST,Jonas,M,1,12.0,<18,41.50,4.67,12.851407,13.7251
826,827,5911,SCHATZ Jacob,SVK Beiertheim,2012.0,55. M U19,749. M,41:43,SCHATZ,Jacob,M,1,14.0,<18,41.72,4.69,12.783639,14.4227
882,883,4693,VON KEITZ Lukas,LuKa,2013.0,56. M U19,800. M,42:06,VON KEITZ,Lukas,M,1,13.0,<18,42.10,4.74,12.668252,15.3994
932,933,3155,ZITTEL Marco,Gymnasium Neureut,2014.0,58. M U19,840. M,42:26,ZITTEL,Marco,M,1,12.0,<18,42.43,4.77,12.569724,16.2714
933,934,553,BÄUMER Bruno,NaN,2014.0,59. M U19,841. M,42:26,BÄUMER,Bruno,M,1,12.0,<18,42.43,4.77,12.569724,16.2888
964,965,70,BÄR Sebastian,LG Rülzheim,2013.0,61. M U19,864. M,42:37,BÄR,Sebastian,M,1,13.0,<18,42.62,4.79,12.513688,16.8294
1070,1071,3123,LÜCK Justus,Gymnasium Neureut,2012.0,68. M U19,951. M,43:12,LÜCK,Justus,M,1,14.0,<18,43.20,4.86,12.345681,18.6781
1110,1111,3109,KRÄTZ Anton,Gymnasium Neureut,2012.0,70. M U19,983. M,43:23,KRÄTZ,Anton,M,1,14.0,<18,43.38,4.88,12.294454,19.3757
1504,1505,3126,LUDWIG Tom,Gymnasium Neureut,2013.0,86. M U19,1298. M,45:32,LUDWIG,Tom,M,1,13.0,<18,45.53,5.12,11.713890,26.2469
1544,1545,945,HOFACKER David,NaN,2014.0,88. M U19,1328. M,45:45,HOFACKER,David,M,1,12.0,<18,45.75,5.15,11.657561,26.9445
1788,1789,4567,EBERLE Luka,Lauftreff Wiesental,2013.0,96. M U19,1512. M,46:59,EBERLE,Luka,M,1,13.0,<18,46.98,5.29,11.352350,31.1999